### ISSUE TITLE
npmStart doesn't work

### ISSUE THREAD

**Issue by ateyssandier** [mukeshsoni/react-telephone-input#130]
It looks like the `start` command was removed from `package.json` and you can no longer run locally

**Comment by mukeshsoni** [comment]
@ateyssandier yeah, it previously depended on `react-component-gulp-tasks` package which didn't work with webpack and was making it difficult for me to use enzyme (because of some dependency clash). I realized that `react-component-gulp-tasks` was anyways too much for my requirements and wanted to simplify the process. I took care of it partially and never got down to update the `start` command and `publish` command. I don't have enough free time on my hands right now to take care of the open source projects.

Feel free to send in a PR. Thanks!!

**Comment by mukeshsoni** [comment]
@ateyssandier I have fixed the `npm start` problem. It will now start a server on `localhost:3000` and you can test all changes to src/ReactTelephoneInput.js there.
