### ISSUE TITLE
kazakhstan phone numbers works incorrect 

### ISSUE THREAD

**Issue by sklevtsov-pyrus** [mukeshsoni/react-telephone-input#232]
+7 717 ..., 
+7-313 ...
show russian flag
expect kazakhstan flag

**Comment by mukeshsoni** [comment]
Bot Russia and Kazakhstan flags seem to have same dial code. So it's not wrong. Just that the priorities are set as 0 for russia 
https://github.com/mukeshsoni/country-telephone-data/blob/master/country_telephone_data.js#L252

And 1 for Kazakhstan  https://github.com/mukeshsoni/country-telephone-data/blob/master/country_telephone_data.js#L184

If we make the priorities same for both, then Kazakhstan will be picked since it comes before Russia in the list.

@sklevtsov-pyrus You can raise a PR on https://github.com/mukeshsoni/country-telephone-data repo.
