### ISSUE TITLE
The value does not get added to the Redux Form v6. 

### ISSUE THREAD

**Issue by Uthpala** [mukeshsoni/react-telephone-input#90]

**Comment by mukeshsoni** [comment]
@Uthpala Can you please provide details? A working example with code would be awesome

**Comment by erikras** [comment]
The way you would do it is:
```jsx
const renderTelephoneInput = ({ input, ...custom }) =>
  <ReactTelInput {...input} {...custom}/>
```
and then
```jsx
<Field name="phone" component={renderTelephoneInput}/>
```
But when I try that, it doesn't work the way I would expect it to. Redux Form registers each change properly and passes in the current value, but it seems like `react-telephone-input` isn't prepared to be a "controlled" input which gets an updated `value` prop on every change. 😕

**Comment by mukeshsoni** [comment]
So it comes via the `value` prop?

**Comment by Uthpala** [comment]
The redux form passes the value prop to the ReactTelInput but the issue here is that it doesn't get updated. It is not a controlled input. 

All that should be done is to make the <ReactTelInput > use the value prop as its value. Not something else. Once that is done it work with redux form.

**Comment by mukeshsoni** [comment]
it is being used (https://github.com/mukeshsoni/react-telephone-input/blob/master/src/ReactTelephoneInput.js#L355), but i guess not in the correct way. Will try to fix it tomorrow.

**Comment by mukeshsoni** [comment]
@Uthpala Can you test out version 3.7.2 and let me know if that works?

**Comment by Uthpala** [comment]
@mukeshsoni Sure will do. But I can only do it in another 8 or 9 hours. I will post the results here once i do. Thanks

**Comment by msaglietto** [comment]
Nice that was a quick response .. but it may caused some issues  ..

I have a form working with version 3.5.0 but after running npm install (well yarn) it installed the 3.7.2 (it was set as ^) and now when you do on blur in the component the field get cleared

I debugged the code and I can see this on the code you posted:
```
 if(props.value !== this.props.value) {
    inputNumber = props.initialValue
 } else if(props.initialValue !== this.props.initialValue) {
    inputNumber = props.initialValue
 } else {
    inputNumber = ''
 }
```
What is happening props.value is === this.props.value  (it get update by the onChange callback)
The initialValue are the same also .. so it ends up with inputNumber = '' and clearing the input 

To reproduce it what I do is:
1.  Click on the field type something
2. Click outside of the field (triggers on blur)
3. Click inside of the field
4. Click outside of the field

But thing get even weird when I have 2 ReactTelInput .. because I do onBlur for one input and the mapStateToProps is executed in both fields .. but that my be a problem of how I am doing the update I need to check .. the strange thing is that it was working on 3.5.0

I am using it wrong by updating the value on onChange and onBlur? 

Should I put my controlled value on initialValue instead of value? 

Thanks

**Comment by gbrassey** [comment]
I'm having similar issues with v3.7.2 and redux-form v5.3.
```
        if(props.value !== this.props.value) {
          inputNumber = props.initialValue
        } else if(props.initialValue !== this.props.initialValue) {
          inputNumber = props.initialValue
        } else {
          inputNumber = ''
        }
```

Seems like this is killing the inputNumber when the value and initialValue props don't change but other props do — like onBlur. Should the final else just return without changing state?

**Comment by mukeshsoni** [comment]
@msaglietto @gbrassey 
Yeah, that piece of code is not thought out well.

If something is a controlled component, it will have a `value` set on props.

One solution could be changing the first check to `if(props.value) { inputNumber = props.value }`

Another could be to not call the same _mapStateToProps in both `getInitialState` and `componentWillReceiveProps`. Makes the checks a little more tricky.

Hmm, let me think a little. Let me know if you have any solution in mind which works for both controlled and non-controlled components.

**Comment by mukeshsoni** [comment]
How about this? 

```
_mapPropsToState(props, firstCall = false) {
        let inputNumber;

        if(props.value) {
            inputNumber = props.value
        } else if(props.initialValue && firstCall) {
            inputNumber = props.initialValue
        } else if(this.state && this.state.formatNumber && this.state.formatNumber.length > 0) {
            inputNumber = this.state.formattedNumber.replace(/\D/g, '')
        } else {
            inputNumber = ''
        }
```

**Comment by mukeshsoni** [comment]
I have cut a release (3.7.3) with the above code. I should probably write a test for controlled component scenario but don't know a good way to do that too ⭕️

**Comment by Uthpala** [comment]
Thanks mate just tried out v3.7.3 and it works 

Cheers.

**Comment by mukeshsoni** [comment]
Cheers @Uthpala

**Comment by msaglietto** [comment]
It worked for me too .. thanks =)
